### ISSUE TITLE
Is there any way to merge the same institutions with different names? 

### ISSUE THREAD

**Issue by lzlzlizi** [cqql/icml-nips-iclr-dataset#1]
Hey, thank for your data, it is awesome!
I am trying to build a network for institutions and use edges to represent collaboration. However, the data contains the same institutions with different names, eg, UCB = UC Berkely = University of California, Berkely. So, my question is that do you know if there is any quick fix of these problems or if there is another same database that may have cleaner data?
Thanks!

**Comment by martenlienen** [comment]
Hey,
the institutions are just the way that the authors entered them when submitting their papers. To clean it up, you would have to define your own mapping from names to institution. I think that [csrankings.org](https://csrankings.org) has a some clean data. In the footer they say that they got it from DBLP. However, they only have tenure-track faculty and, I believe, they maintain their own list of disambiguations.

**Comment by lzlzlizi** [comment]
Thanks for your reply. I will give it(csrankings.org) a try latter.
