### ISSUE TITLE
where is dataclasses?

### ISSUE THREAD

**Issue by xiaohanhaowei** [cqql/icml-nips-iclr-dataset#2]
RT, when I use the instruction followed by the content introduced in "README.md", I can't find the dataclasses.
Here is the mistake:
> from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

Hope your early reply.

**Comment by martenlienen** [comment]
[dataclasses](https://docs.python.org/3/library/dataclasses.html) are a new-ish python feature and require at least python 3.7.
