### ISSUE TITLE
Script doesn't work because of CSS change

### ISSUE THREAD

**Issue by patrickmineault** [cqql/icml-nips-iclr-dataset#3]
It appears the script currently fails to scrape because the `Poster` CSS class was renamed `poster`

https://github.com/martenlienen/icml-nips-iclr-dataset/blob/5284afdf419c89923f04279f77443f4510655165/scrape.py#L51

I changed `Poster` -> `poster` and ran the code successfully.

**Comment by martenlienen** [comment]
Did they also update it in older versions of the website? So can the updated script still scrape the old data?

**Comment by patrickmineault** [comment]
Yes, it works for the old versions as well.

**Comment by martenlienen** [comment]
Thanks, I have updated the script
